### ISSUE TITLE
Larger Resolution Icons at the same menu / screen / monitor size (e.g. 128x128 icons)

### ISSUE THREAD

**Issue by WithinAmnesia** [flareteam/flare-game#879]
I have a deep desire for better icon resolution possibility for the Flare Engine (e.g. 128 x 128 pixel icons).

I know that Diablo II has larger icon sizes where as the largest icon in the original Diablo II used 32 x 32 sized icons for one 'icon tile' out of a possible 2 x 3 = 6 'icon tile'
Examples:
- Diablo II Ring: https://diablo.fandom.com/wiki/List_of_Unique_Rings_(Diablo_II)?file=D2-Ring1.gif (32 x 32)
- Diablo II Body Armour: https://diablo.fandom.com/wiki/List_of_Unique_Body_Armor_(Diablo_II)?file=D2-u-Goldskin.gif (64 x 96 [technically 62 x 91 but still 2 x 3 'icon tiles' of 32 x 32])

World of Warcraft uses item icons of 56 x 56 (64 x 64 with borders): https://wow.zamimg.com/images/wow/icons/large/classicon_warrior.jpg (64 x 64 'barely looks okay')

Baldur's Gate uses 64 x 64 pixel 'icon tile' size and I can very much tell the difference of 32 x 32 compared to 64 x 64 (for I have made many Baldur's Gate item icons: https://www.deviantart.com/withinamnesia/gallery/51118284/baldur-s-gate-path-of-the-lost-odyssey )

Path of Exile uses 78 x 78 item 'icon tile' sizes; Path of Exile is kind of a retread of Diablo II but with more content. The ~same inventory system of items being made as Diablo II 'icon tiles' ranging from 1 x 1 'icon tile' to 2 x 4 'icon tile'. So in theory 2 x 78 = 156 and 4 x 78 = 312.
Examples:
- Path of Exile Ring: https://pathofexile.fandom.com/wiki/Vermillion_Ring?file=Vermillion_Ring_inventory_icon.png (82 x 82 is an example of being larger than the minimum but smaller than the maximum of 78 x 4 = 312)
- Path of Exile Body Armour: https://pathofexile.fandom.com/wiki/Glorious_Plate?file=Glorious_Plate_inventory_icon.png (156 x 234 which is 78 x 2 = 156 and 78 x 3 = 234)
- Path of Exile Bow: https://pathofexile.fandom.com/wiki/Reach_of_the_Council?file=Reach_of_the_Council_inventory_icon.png (156 x 312, which is 78 x 2 = 156 and 78 x 4 = 312)

Diablo II Resurrected uses 98 x 98 pixel 'icon tile' size 
Ring: https://www.purediablo.com/wp-content/uploads/2021/04/ring4.png (98 x 98, 98 x 1 = 98)
Body Armour: https://www.purediablo.com/wp-content/uploads/2021/04/goldskin.png (196 x 294, 98 x 2 = 196 and 98 x 3 = 294)

All of these games pretty much use the same size / ~'screen real-estate' on the player's monitor to display roughly the same size item icons in roughly the same icon density per 'icon tile'.

I am hoping that Flare engine can somehow have the option to support higher resolution 'icon tiles' (128 x 128?). Yet keep the inventory 'icon tiles' using the same ~monitor / 'screen real-estate' as before; same proportions yet with higher definition. The old art is in 32 x 32 pixels per 'icon tile' so if they were could be scaled up / up-scaled / simply by multiplying the icons by ~4 to make 32 x 32 into 128 x 128. All of the old icons could stay the same and look the same yet the whole engine could hopefully render with 4 times more detail (with higher resolution [128 x 128 icons] art assets added in piece meal / bit by bit to start).

To have the old icons still be usable in a 4 times higher resolution display rendered for the Flare engine (~'just') take the "icons.png" file and times it by 4 from 256 x 1,024 into 1,024 x 4,096 [do not use 'soft edges']. All other needed preexisting Flare engine art (the menu art files) can be up scaled / image resolution multiplied by 4 to scale up the art assets images to work at higher resolutions. This saves a lot of work (new high resolution 128 x 128 Flare icons that can optionally be done later) for the Flare engine rendered resolution can be multiplied by 4 without needing to create more high resolution art assets from scratch to start. Does the ~'Flare HD' prototype increase the screen resolution rendered or does it just zoom in and use bigger sprites?

I hope that the Flare engine could support higher resolution 'icon tiles' (by example 128 x 128; or the current 32 x 32 multiplied by 4) so that as 4k monitors become standard and eventually 'old tech' by the next decade / 2030's that what ever games made with the Flare engine can have a chance / the option to support higher resolution 'icon tiles' (if not higher resolution art in general) to hopefully stand the test of time.

**Comment by dorkster** [comment]
_(There's no engine limitation here, so I moved this to flare-game)_

We actually have 64x64 (60x60 with a 2px border) icons in the art_src/icons folder: [icons.xcf](https://github.com/flareteam/flare-game/blob/master/art_src/icons/icons.xcf)

Many of the icons are 3D renders that have been painted over, and there aren't any larger sources. So 64x64 is what we have to work with.

We scale the icons down to 32x32 because that's what fits with the rest of our current art assets. Re-did all the assets at 2x size, *then* we could use 64x64 icons. Doing this is not trivial:

- The 3D assets would need to be re-rendered at 2x. The workflow for this is currently a mess. Ideally, we want to have a Python script in each Blender file that will spit out exactly what the engine wants. But as it stands now, the steps required vary from file to file.
- Some of the "3D" assets are renders from OGA that don't have 3D source files, such as the Thunderstrike spell.
- The 2D UI assets don't have larger sources. There are the Wandercall assets, but they are incomplete. Also, the menu borders are too big, meaning that our current icon density wouldn't fit. We'd probably be better off making something designed specifically for flare-game.

The current assets are "good enough" for now. Doing an "HD" version of the art has been on the back burner for years, and I predict it will stay that way for a while.

----

PS, here's a screenshot of Wandercall to show what 64x64 icons can look like:

![Screenshot_20220111_084805](https://user-images.githubusercontent.com/913982/148962313-a4729503-cc2b-48c1-a899-f2a9508d96bb.png)

**Comment by WithinAmnesia** [comment]
Okay I noticed that the Flare engine / game resolution is at a minimum of I think '# display resolution. 640x480 minimum': https://github.com/flareteam/flare-engine/blob/8769888f08c21ecf197a08fed2879d770c7571c0/mods/gcw0_defaults/engine/default_settings.txt (or mods\default\engine\resolutions.txt)
I have had a 4k Monitor of 3840 x 2160 resolution since 2016. In windowed mode Flare takes less than a quarter of my screen (with a current 'on the market' 8K monitor that will become less than an 8th of the screen). Is this explained by the '# display resolution 640x480 minimum' of the Flare Engine / Game?

If I were to multiply by 4 the Flare minimum resolution from 640 x 480 to 2,560 x 1,920 would all of the art assets crash because they are smaller scale (like 32 x 32 icons)?

If this is possible to increase the pixel density / 4 times the minimum screen resolution for Flare I would be willing to do the menu / art work, ~'place holders'(?) where for example a 32 x 32 icon turns into a 128 x 128 icon but with the same full screen real-estate as before but with the support of later adding in full detail 128 x 128 icons. I am wondering how to get Flare working with 4 times the resolution as the minimum resolution and what needs to be done art wise to make it not crash; even if it looks the same as before but technically it is running old 32 x 32 icons up-scaled / multiplied by 4 into 128 x 128 icons. Or is there major coding resolution issues that prevent smoothly implementing all of the old art up-scaled by 4 with 4 times the minimum screen resolution so that the pixel density is increased by 4 times? If I can help with the art up-sizing I can do that, although I am in the dark as to what steps would be need to be taken and in what order on the engine side of things. If the minimum screen resolution is multiplied by 4, old art assets can be up-scaled / enlarged without tearing for one old pixel can be split into 4 pixels and still look the same but the Flare game / engine could then support new assets to eventually replace the old assets bit by bit that are made from the start with the higher detail / using 128 x 128 pixel icons from the start.

**Comment by WithinAmnesia** [comment]
Also how do I tinker with (mods\default\engine\resolutions.txt)
"# Screen and icon resolution settings

menu_frame_width=640
menu_frame_height=480

icon_size=32

required_width=640
required_height=480

virtual_height=480,600
virtual_dpi=91.754738"

If I multiply everything by 4 it looks like
"# Screen and icon resolution settings

menu_frame_width=2560
menu_frame_height=1920

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920,2400
virtual_dpi=367.018952"

Will this break everything? Hmmmn, there is at least one way to find out XD.

**Comment by dorkster** [comment]
The fantasycore mod actually has its own resolutions.txt defined to suit the art assets: https://github.com/flareteam/flare-game/blob/master/mods/fantasycore/engine/resolutions.txt

The `virtual_height` is what determines the resolution the game actually gets rendered at. You can see that fantasycore ranges from 480 to 768. What this means is that when the window height is taller than 768 pixels, the game begins to get scaled up to fit the window. Below that point, the game is rendered 1:1. So if you had assets 4x the current size, 1920 should be your minimum virtual height.

`virtual_dpi` modifies the scaling based on screen DPI. You can ignore this, and you should in fact turn off "DPI Scaling" in the video options if you plan on experimenting with resolutions.

The `required_width` and `required_height` are for the minimum window size. It's not essential to changes these right away, but you'll want to find a minimum that works with your assets.

The `menu_frame_width` and `menu_frame_height` describe an invisible box that is centered on the screen. It is used to position the main, new game, load game, and config menus. Changing these settings means that the menu layouts need to be updated to account for the new size.

`icon_size` is self explanatory. But remember that the actual size of icons in icons.png should match it.

**Comment by WithinAmnesia** [comment]
Okay so all mods with engine/resolutions.txt must be all the same (mods/default/engine/resolutions.txt, mod/fantasycore/engine/resolutions.txt etc.?)

Round 2.0
"# Screen and icon resolution settings

menu_frame_width=640 [not 2560, keep these the same and somehow fight / tinker with these later in a version 2.0?]
menu_frame_height=480 [not 1920, keep these the same and somehow fight / tinker with these later in a version 2.0?]

icon_size=128 [make icons.png 4 times the size to match?]

required_width=2560 [think could work for now / tinker with this later?]
required_height=1920 [think could work for now / tinker with this later?]

virtual_height=1920  [2400 does get taken out, or is it 1920,2400?]
virtual_dpi=91.754738 [don't touch this / turn it off?]

This should work? I will try it out; round 2.0 wish myself luck XD
![icons(x4)](https://user-images.githubusercontent.com/86871191/149054732-acf81b35-0c13-40ed-926a-cc2d5ccb29b2.png)
.

**Comment by WithinAmnesia** [comment]
Crap how do I do spoilers that is a very big image XD.

**Comment by dorkster** [comment]
> Crap how do I do spoilers that is a very big image XD.

You can change the embedded image to a link by removing the preceding exclamation point. I fixed it for you.

**Comment by WithinAmnesia** [comment]
Oh thank you.

**Comment by WithinAmnesia** [comment]
"# Screen and icon resolution settings

menu_frame_width=640
menu_frame_height=480

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920
virtual_dpi=91.754738" [DPI is off]

I am still getting the broken starting menu with no buttons (how do I set up the menu?). I could try just using the bigger icons although this should just make bigger icons and not increase pixel density.

**Comment by WithinAmnesia** [comment]
I wonder if the virtual height is breaking the menus (something like 4 times the resolution but still small menus)?

Should I try to tinker with the menus in (mods\fantasycore\menus) to try to make them bigger by 4 and also use this resolutions.txt

Would this work if I tinkered with the menu settings?
"# Screen and icon resolution settings

menu_frame_width=2560
menu_frame_height=1920

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920
virtual_dpi=91.754738" [DPI is off]"

**Comment by dorkster** [comment]
I tried the exact same settings for resolutions.txt and have no issue with the buttons on the title screen. The configuration for that menu is `mods/default/menus/gametitle.txt`, but you shouldn't need to change anything in there. The buttons are positioned relative to the bottom of the screen.

**Comment by WithinAmnesia** [comment]
(mods\default\menus\gametitle.txt) it has to be this one?

**Comment by WithinAmnesia** [comment]
Hmmm.

**Comment by WithinAmnesia** [comment]
I will put all resolutions.txt to:
"# Screen and icon resolution settings

menu_frame_width=640
menu_frame_height=480

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920
virtual_dpi=91.754738" [DPI is off] and see if I missed a step before.

**Comment by dorkster** [comment]
Both work for me.

For something else to try, you can change all the instances of `bottom` to `center` in `mods/default/menus/gametitle.txt`. This should put the buttons near the logo.

**Comment by WithinAmnesia** [comment]
(mods/default/menus/gametitle.txt)
"logo=images/menus/logo.png,0,0,center

play_pos=0,-84,bottom
config_pos=0,-56,bottom
credits_pos=0,-28,bottom
exit_pos=0,0,bottom"

To this?

logo=images/menus/logo.png,0,0,center

play_pos=0,-84,center
config_pos=0,-56,center
credits_pos=0,-28,center
exit_pos=0,0,center"

**Comment by dorkster** [comment]
Yes

**Comment by WithinAmnesia** [comment]
This works, the title menu is back.
"logo=images/menus/logo.png,0,0,center

play_pos=0,-84,center
config_pos=0,-56,center
credits_pos=0,-28,center
exit_pos=0,0,center"

**Comment by WithinAmnesia** [comment]
I will try that will all of the ~'broken' / misaligned menus if i can to get them visible.

**Comment by dorkster** [comment]
Dumb question, but are you sure you have the entire window on screen? You could try maximizing the window to see if things at the bottom start to show up.

**Comment by WithinAmnesia** [comment]
Okay I am making progress with the menu positioning with the bigger screen resolution. I think I can get the menus to align now. The use of ",center" really helps.

**Comment by WithinAmnesia** [comment]
"Dumb question, but are you sure you have the entire window on screen? You could try maximizing the window to see if things at the bottom start to show up." I am not sure. It may not be, I cannot see the window edges then again once I get the menu working I can see if I have full screen on or off. It looks like full screen but I am not 100% sure.

**Comment by WithinAmnesia** [comment]
What is the pause / escape menu called in a menu text file?

**Comment by dorkster** [comment]
`mods/default/menus/config.txt`

**Comment by WithinAmnesia** [comment]
(mods\fantasycore\menus\exit.txt) what is this?

**Comment by dorkster** [comment]
Oh, that's the file for the old pause menu (before the config menu replaced it). It's no longer used, so I'll remove it.

**Comment by WithinAmnesia** [comment]
Okay. So config.txt is pause menu? So I can pause the game but the menu is not anywhere to be seen.

(mods\default\menus\config.txt)
"# Configuration menu Widgets Definitions.
# Coordinates should be integer, representing absolute position on 640x480 screen
# First two values are for label position (x,y) and two last for control (x,y)
# Buttons don't have separate labels

button_ok=0,-56,center
button_defaults=0,-28,center
button_cancel=0,0,center

listbox_scrollbar_offset=2

# scrollpane values are positions x, y and sizes width, height
# scrollpane=0,4,600,320
scrollpane=-6,-6,616,344
scrollpane_padding=80,40
# scrollpane_bg_color=26,26,26,127
scrollpane_separator_color=63,63,63

[mods]
activemods=456,16,384,32
inactivemods=136,16,64,32
activemods_shiftup=544,128
activemods_shiftdown=544,160
activemods_deactivate=224,160
inactivemods_activate=224,128"

Do I put ",center" everywhere or something?

**Comment by dorkster** [comment]
All of the contents of the config menu are placed inside the menu frame. If you have `menu_frame_width=640` and `menu_frame_height=480` in your resolutions.txt, the config menu should be centered on the screen already.

**Comment by WithinAmnesia** [comment]
I have made the Icons too big lol. I need to make the icons file x2 not x4 for I turned one pixel of the old icons into 16 pixel not 4 lol (4x4, it should be 2x2 XD). 1 Sec. I have duplo when I should have legos XD.

"All of the contents of the config menu are placed inside the menu frame. If you have menu_frame_width=640 and menu_frame_height=480 in your resolutions.txt" I will make it so XD.

**Comment by WithinAmnesia** [comment]
"If you have menu_frame_width=640 and menu_frame_height=480"
*check resolutions*
"# Screen and icon resolution settings

menu_frame_width=2560 [HMM...]
menu_frame_height=1920 [...MMMN]

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920
virtual_dpi=91.754738
"
AHH yes lol XD 1 sec.

**Comment by WithinAmnesia** [comment]
"Dumb question, but are you sure you have the entire window on screen? You could try maximizing the window to see if things at the bottom start to show up."

https://cdn.discordapp.com/attachments/872743295003000852/930674681172873256/unknown.png
Woah lol maybe if I had an 8k monitor lol. Yeah It is a bit too big XD.

**Comment by WithinAmnesia** [comment]
I will turn virtual_height=1920 to virtual_height=960 lol. I think I messed up 2x2 = 4 into 4 x 4 = 16 XD.

**Comment by WithinAmnesia** [comment]
https://cdn.discordapp.com/attachments/872743295003000852/930676601283293244/unknown.png well that did something but it reminds myself of https://knowyourmeme.com/memes/wide-putin-walking-its-him

**Comment by dorkster** [comment]
2560x1920 should fit on a 4K (3840x2160) monitor, no?

I think I figured it out! If you have scaling on in Windows, Flare gets scaled up, too. I just tried this in a VM at 150% windows scaling, and setting the resolutions.txt to match my monitor made the title buttons go off screen.

**Comment by WithinAmnesia** [comment]
If you have scaling on in Windows.. Hmm how do I change that?

**Comment by dorkster** [comment]
Settings > System > Display > Scale and Layout > Change the size of text, apps, and other items

**Comment by WithinAmnesia** [comment]
[image](https://user-images.githubusercontent.com/86871191/149063656-9d83aad0-ff07-4dd8-917f-5d4253068609.png) this?

**Comment by WithinAmnesia** [comment]
I this have this 
[Uploading image.png…]()

**Comment by dorkster** [comment]
Yes, that's the setting. You probably don't want to change that, so my recommendation is to target a lower resolution for Flare. Try 720p, 960p, or 1080p as a start.

**Comment by WithinAmnesia** [comment]
Hold on 
[Uploading image.png…]() (windowed)
[Uploading image.png…]() (fullscreen) It looks like the full screen is twice as large as the windowed like the resolution is 8k?

**Comment by dorkster** [comment]
I think you need to wait for your images to finish uploading. The upload status is at the bottom of the comment box.

**Comment by WithinAmnesia** [comment]
So this:
"# Screen and icon resolution settings

menu_frame_width=640
menu_frame_height=480

icon_size=128

required_width=2560
required_height=1920

virtual_height=1920
virtual_dpi=91.754738"

To this?

"# Screen and icon resolution settings

menu_frame_width=640
menu_frame_height=480

icon_size=128

required_width=2560 [these stay the same or change them?]
required_height=1920 [these stay the same or change them?]

virtual_height=1080 [960 kind of made it 'wide putin', should it not be 1920?]
virtual_dpi=91.754738"

**Comment by dorkster** [comment]
Oh, I found a work-around to disable Windows' scaling for just Flare. Edit the (or make a new) shortcut to Flare and go to Compatibility > Change high DPI settings

<img width="512" alt="scaling" src="https://user-images.githubusercontent.com/913982/149064763-aec8b82a-10e0-47b7-9ee4-86d17c471ab4.png">

**Comment by WithinAmnesia** [comment]
https://cdn.discordapp.com/attachments/872743295003000852/930682823571042355/unknown.png (windowed)
https://cdn.discordapp.com/attachments/872743295003000852/930682872719880212/unknown.png (full screen)

**Comment by WithinAmnesia** [comment]
https://cdn.discordapp.com/attachments/872743295003000852/930683459767263292/unknown.png That worked.

**Comment by dorkster** [comment]
Great! Perhaps I need to look into setting [SDL_HINT_VIDEO_HIDPI_DISABLED](https://wiki.libsdl.org/SDL_HINT_VIDEO_HIGHDPI_DISABLED).

**Comment by WithinAmnesia** [comment]
https://cdn.discordapp.com/attachments/872743295003000852/930684571664670780/unknown.png 128 x 128 icons are working now.

**Comment by WithinAmnesia** [comment]
https://cdn.discordapp.com/attachments/872743295003000852/930685038562009158/unknown.png They are indeed working.

**Comment by dorkster** [comment]
Looks like the icons are working. They're just a bit big for the rest of the game :)

**Comment by WithinAmnesia** [comment]
Yeah I also have 100 inventory spaces in this prototype XD.

**Comment by WithinAmnesia** [comment]
That is really excellent, the 128 x128 icons are working. 


https://cdn.discordapp.com/attachments/872743295003000852/930688541720211466/unknown.png
Now with all of the screen resolution is it possible to upscale all the assets by x 4 and have it loot the same as before with the old up scaled assets but have 4 times the pixel density so that new assets can be made to gradually replace the up-scaled low resolution assets?

I am not sure how that would work but if the tiles and spirits / animations are 4 times larger (x 4 sup scaled) they would look the same but have 4 times the pixel density / resolution. Now I understand icons are one thing and tilesets and animations are another.

Although how complex would it be for 'FlareHD light' / Flare x 4? If I made all of the old art assets scaled up the same as the icons (x4 in scale) would this work with making the tilesets and animations? How would the Flare engine be able to run these 4 times larger tileset and animations? Is it very complex? Or is it something doable? Can this idea even work in the Flare engine with the rest of Flare art be up-scaled / enlarged by 4 times to match the icons and take advantage of the 4 times increased pixel density?

This FlareHD light / ~'Flare x 4' would not require new art assets effectively (just simple scaling to nearest pixel edits). I am wondering if it would be a nightmare to render the tilesets and animations 4 times larger to match the x 4 time resolution like the icons?

Is this a reasonable idea or is it out for lunch XD? I know making new art is a hard thing to do but up-scaled art could be easier? I am not 100% sure how Wandercall handled the resolution although I like the original scale of Flare but I am hoping for x4 times more pixel density; yet using basically the same but x 4 up scaled art assets to start ~'Flare x 4'?

Is this asking too much and or is there a huge unseen complexity that is hard to over come? I am wondering if 'Flare x 4' can be achieved or not in a reasonable manner. As in kind of like what happened here with the 128 x 128 icons success; but for the tilesets and animations. Is it possible to run all the original art assets of Flare yet with x 4 the pixel density and hope they still work in the Flare engine?

If so then this could open the doors for the community to make higher resolution 'FlareHD' assets but at a reasonable pace with still using original Flare x4 enlarged / up-scaled assets as placeholders. This could take Flare from 2000's art into the 2020's art and add decades of life to the art and I think with x 4 the pixel density that the Flare engine can make some really amazing games. Although it all comes down to figuring if it can be done early enough I feel. I really hope that 'Flare x 4' can be reasonable to do for it can lead to some amazing looking games that graphically could stand the test of time.

**Comment by Danimal696** [comment]
Sorry to crash conversation, my two cents, WithinAmnesia your screen is too big for your own good ; ).

For the art upscaling there are some solutions, first there is an "item camera setup" in the art repo (git-flare\flare-game\art_src\icons\artifacts) it works with any item, save for needing importing and manually rotating of the item; it ouputs whatever size you want, the bad thing is that some items are too "plain" when rendered. The plain clothes for example, so in the past someone painted over them to improve their looks, you might need to play around with noise textures/normals to avoid hand painting.
Other solution would be AI upscaling software, sorry but i only know it exists, nothing else. But it could potentially upscale everything by itself.

**Comment by WithinAmnesia** [comment]
Screen sizes are only going up though; I got my 4k screen in 2016 and now there are 5k and 8k on the market and soon more with the high pixel density / very high resolution VR technology taking off. All of the Flare graphics will be very dated come 2030's, they already look very 2000's and I am hoping that with some technically work / know-how the framework for 'Flare x 4' can be implemented / tested so as to have a viable realistic route to FlareHD and or new games with new assets.

It will not look HD right away but if the framework is there then it can be made into smaller tasks and done over time and increasing the chance of success verses potentially forever being on the back burner. I know it sucks to do but there are only so many assets to x 4 enlarge and if 'Flare x 4' can be made before I go and build a massive game I can make all new assets with graphics that will be high resolution and add decades of life to the game.

I do not want to go through retrofitting hell again with making an RPG so I'd rather get this last major issue dealt with (if it even can be reasonably dealt with) and I am really hoping that this is the last major 'engine' / Flare feature / upgrade I have to do before I can start mass producing levels and assets and start hammering out an RPG on a massive scale.

**Comment by WithinAmnesia** [comment]
This should be possible with Flare 1.13(R.C.2). Although the DPI is still an issue and requires a manual override still https://github.com/flareteam/flare-game/discussions/887#discussioncomment-2020131 . If the DPI manual override can be solved (to have non-buggy start up / easy player presentation) than this issue should be possible and working for 128x128 icons and Flare x 4 G.U.I. / H.U.D. components.

**Comment by WithinAmnesia** [comment]
I'll make a DPI issue to focus on that. I should close this issue, 128x128 icons work, it is just that the DPI is not automatic, which is an annoying issue but a work around does exist (manually changing the DPI override for windows).
